module Map
  class MajorMap

    attr_reader :map

    def initialize
      @map = {
        a: {
          1  => nil,
          3  => nil,
          5  => nil,
          7  => nil,
          9  => nil,
          11 => nil,
          13 => nil,
          15 => nil,
          17 => nil,
          19 => Tile.new(color: :red),
          21 => nil,
          23 => nil,
          25 => Tile.new(color: :red),
        },
        b: {
          0  => nil,
          2  => nil,
          4  => nil,
          6  => nil,
          8  => nil,
          10 => nil,
          12 => nil,
          14 => nil,
          16 => Tile.new(mountain: 60),
          18 => Tile.new(label: 'Freistadt', towns: 1, mountain: 50),
          20 => Tile.new(mountain: 50),
          22 => Tile.new(label: 'Stockerau Klosterneuburg', towns: 2, mountain: 50),
          24 => Tile.new,
          26 => Tile.new,
        },
        c: {
          1  => nil,
          3  => nil,
          5  => nil,
          7  => nil,
          9  => nil,
          11 => nil,
          13 => nil,
          15 => Tile.new(label: 'Reid', towns: 1),
          17 => Tile.new(label: 'Linz', city: 'KB'),
          19 => Tile.new,
          21 => Tile.new,
          23 => Tile.new,
          25 => Tile.new,
          27 => Tile.new,
        },
        d: {
          0  => Tile.new,
          2  => nil,
          4  => Tile.new(color: :red),
          6  => nil,
          8  => nil,
          10 => nil,
          12 => Tile.new(color: :red),
          14 => Tile.new,
          16 => Tile.new,
          18 => Tile.new,
          20 => Tile.new,
          22 => Tile.new,
          24 => Tile.new,
          26 => Tile.new,
          28 => Tile.new,
        },
        e: {
          1  => Tile.new,
          3  => Tile.new,
          5  => Tile.new,
          7  => Tile.new,
          9  => Tile.new,
          11 => Tile.new,
          13 => Tile.new,
          15 => Tile.new(label: 'Reid', towns: 1),
          17 => Tile.new(label: 'Linz', city: 'KB'),
          19 => Tile.new,
          21 => Tile.new,
          23 => Tile.new,
          25 => Tile.new,
          27 => Tile.new,
        },
        f: {
          0  => nil,
          2  => Tile.new,
          4  => Tile.new,
          6  => Tile.new,
          8  => Tile.new,
          10 => Tile.new,
          12 => Tile.new,
          14 => Tile.new,
          16 => Tile.new,
          18 => Tile.new,
          20 => Tile.new,
          22 => Tile.new,
          24 => Tile.new,
          26 => nil,
          28 => Tile.new,
        },
        g: {
          1  => Tile.new,
          3  => Tile.new,
          5  => Tile.new,
          7  => Tile.new,
          9  => Tile.new,
          11 => Tile.new,
          13 => Tile.new,
          15 => Tile.new(label: 'Reid', towns: 1),
          17 => Tile.new(label: 'Linz', city: 'KB'),
          19 => Tile.new,
          21 => Tile.new,
          23 => Tile.new,
        },
        h: {
          0  => nil,
          2  => nil,
          4  => nil,
          6  => nil,
          8  => nil,
          10 => Tile.new,
          12 => nil,
          14 => Tile.new,
          16 => Tile.new,
          18 => Tile.new,
          20 => Tile.new,
        },
        i: {
          1  => nil,
          3  => nil,
          5  => nil,
          7  => nil,
          9  => nil,
          11 => nil,
          13 => nil,
          15 => Tile.new,
          17 => nil,
          19 => Tile.new,
          21 => nil,
          23 => nil,
        },
      }
    end

    def rows
      map.key
    end

    def cols(row=nil)
      map[row].keys
    end

  end
end
