module Map
  class MajorMap

    attr_reader :map

    def initialize
      @map = {
        a: {
          1  => nil,
          3  => nil,
          5  => nil,
          7  => nil,
          9  => nil,
          11 => nil,
          13 => nil,
          15 => nil,
          17 => nil,
          19 => Tile.new(color: :red),
          21 => Tile.new(noborder: true),
          23 => nil,
          25 => Tile.new(color: :red),
        },
        b: {
          0  => nil,
          2  => nil,
          4  => nil,
          6  => nil,
          8  => nil,
          10 => nil,
          12 => nil,
          14 => nil,
          16 => Tile.new(mountain: 60),
          18 => Tile.new(towns: 1, mountain: 50),
          20 => Tile.new(mountain: 50),
          22 => Tile.new(towns: 2, mountain: 50),
          24 => Tile.new,
          26 => Tile.new,
        },
        c: {
          1  => nil,
          3  => nil,
          5  => nil,
          7  => nil,
          9  => nil,
          11 => nil,
          13 => Tile.new(towns: 1, value: 1, noborder: true),
          15 => Tile.new(towns: 1),
          17 => Tile.new(city: 'KB'),
          19 => Tile.new(river: 50, towns: 1),
          21 => Tile.new(river: 50, towns: 2),
          23 => Tile.new(label: 'Wien', color: :yellow, value: 40),
          25 => Tile.new,
          27 => Tile.new(color: :red),
        },
        d: {
          0  => Tile.new(label: 'Paris', color: :white, value: 90),
          2  => nil,
          4  => Tile.new(color: :red),
          6  => nil,
          8  => nil,
          10 => nil,
          12 => Tile.new(color: :red, value: -10),
          14 => Tile.new(mountain: 70),
          16 => Tile.new(towns: 1),
          18 => Tile.new(towns: 2),
          20 => Tile.new(towns: 2),
          22 => Tile.new(mountain: 50, towns: 2),
          24 => Tile.new(towns: 1),
          26 => Tile.new(towns: 1),
          28 => Tile.new(color: :red),
        },
        e: {
          1  => Tile.new(color: :red),
          3  => Tile.new(city: 'VB'),
          5  => Tile.new(label: 'Außerfernbahn', mountain: 100),
          7  => Tile.new(mountain: 70),
          9  => Tile.new(mountain: 70),
          11 => Tile.new(towns: 2, river: 50),
          13 => Tile.new(city: 'SB'),
          15 => Tile.new(mountain: 90),
          17 => Tile.new(mountain: 100),
          19 => Tile.new(mountain: 90),
          21 => Tile.new(mountain: 120, towns: 2),
          23 => Tile.new(label: 'Semmeringbahn', mountain: 70),
          25 => Tile.new,
          27 => Tile.new(color: :red),
        },
        f: {
          0  => nil,
          2  => Tile.new(towns: 2),
          4  => Tile.new(label: 'Arlbergbahn', mountain: 120),
          6  => Tile.new(towns: 1, river: 50),
          8  => Tile.new(city: 'NT'),
          10 => Tile.new(river: 50),
          12 => Tile.new(tunnel: true),
          14 => Tile.new(tunnel: true, value: 10),
          16 => Tile.new(label: 'Murtalbahn', mountain: 100),
          18 => Tile.new(tunnel: true),
          20 => Tile.new(label: 'Graz-Köflacher Bahn', mountain: 90),
          22 => Tile.new(label: 'Graz', city: true),
          24 => Tile.new(towns: 1),
          26 => nil,
          28 => Tile.new(label: 'Konstantinopel', value: 70, color: :white),
        },
        g: {
          1  => Tile.new(color: :red),
          3  => Tile.new(towns: 1, mountain: 80),
          5  => Tile.new(tunnel: true),
          7  => Tile.new(tunnel: true),
          9  => Tile.new,
          11 => Tile.new(tunnel: true),
          13 => Tile.new(tunnel: true),
          15 => Tile.new(mountain: 80),
          17 => Tile.new(tunnel: true),
          19 => Tile.new,
          21 => Tile.new,
          23 => Tile.new,
        },
        h: {
          0  => nil,
          2  => nil,
          4  => nil,
          6  => nil,
          8  => nil,
          10 => Tile.new(color: :red),
          12 => Tile.new(value: 10, towns: 1, noborder: true),
          14 => Tile.new(mountain: 80),
          16 => Tile.new(mountain: 70, towns: 2),
          18 => Tile.new(city: 'KT'),
          20 => Tile.new,
        },
        i: {
          1  => nil,
          3  => nil,
          5  => nil,
          7  => nil,
          9  => nil,
          11 => nil,
          13 => nil,
          15 => Tile.new(color: :red),
          17 => nil,
          19 => Tile.new(color: :red),
          21 => nil,
          23 => nil,
        },
      }
    end

    def rows
      map.key
    end

    def cols(row=nil)
      map[row].keys
    end

  end
end
